Repository heavy-duty/znap, pull requests merged in 2024-07, with the labels that each got.

#56 feat: OG and Twitter custom images for hats
  TUTORIAL.md
  examples/znap-hats/app/vercel.json
  examples/znap-hats/app/web/app/api/data.json
  examples/znap-hats/app/web/app/api/hats/[id]/route.ts
  examples/znap-hats/app/web/app/hats/[id]/page.tsx
  examples/znap-hats/app/web/app/hats/page.tsx
  examples/znap-hats/app/web/app/layout.tsx
  examples/znap-hats/app/web/project.json
  examples/znap-hats/app/web/utils/hat.ts
  examples/znap-hats/collections/my-actions/src/hat_api.rs
Labels: enhancement

#64 chore: nx migrations for nextjs
  examples/znap-hats/app/package.json
  examples/znap-hats/app/web/app/actions.json
  examples/znap-hats/app/web/app/hats/[id]/page.tsx
  examples/znap-hats/app/web/app/manifest.json
Labels: dependencies

#31 fix: znap run example
  .gitignore
  Cargo.toml
  examples/send-donation/Cargo.toml
  examples/send-donation/Znap.toml
  examples/send-donation/collections/my-actions/Cargo.toml
  examples/standalone-shuttle/Cargo.toml
  examples/standalone-shuttle/src/lib.rs
  examples/standalone-tokio/.znap/.gitkeep
  examples/standalone-tokio/Cargo.lock
  examples/standalone-tokio/Cargo.toml
Labels: bug

#79 Pass CI
  znap-cli/src/commands/build.rs
  znap-cli/src/commands/clean.rs
  znap-cli/src/commands/deploy.rs
  znap-cli/src/commands/init.rs
  znap-cli/src/commands/new.rs
  znap-cli/src/commands/serve.rs
  znap-cli/src/commands/test.rs
  znap-cli/src/lib.rs
  znap-cli/src/template/collection_deploy_binary.rs
  znap-cli/src/template/collection_toml.rs
  znap-cli/src/template/new_collection_body.rs
  znap-cli/src/template/new_collection_toml.rs
  znap-cli/src/utils/mod.rs
  znap-syn/src/codegen/action/path.rs
  znap-syn/src/codegen/action/to_metadata.rs
  znap-syn/src/common.rs
  znap-syn/src/parser/action/mod.rs
  znap-syn/src/parser/collection/actions.rs
  znap-syn/src/parser/collection/get_action_fns.rs
  znap-syn/src/parser/collection/mod.rs
  znap-syn/src/parser/collection/post_action_fns.rs
  znap-syn/src/parser/error_code/mod.rs
  znap/src/lib.rs
Labels: ci

#81 Correct path for lib from env variable
  znap-cli/src/utils/mod.rs
Labels: bug, cli

#84 Env context struct
  znap-cli/src/commands/new.rs
  znap-cli/src/commands/serve.rs
  znap-cli/src/commands/test.rs
  znap-cli/src/utils/mod.rs
  znap-syn/src/codegen/collection/handle_get.rs
  znap-syn/src/codegen/collection/handle_post.rs
  znap/src/env.rs
  znap/src/lib.rs
  znap/src/prelude.rs
Labels: core

#82 Generate First tests case
  .github/workflows/ci.yml
  .gitignore
  examples/send-donation/Cargo.lock
  tests/send-donation/Cargo.lock
  tests/send-donation/Cargo.toml
  tests/send-donation/README.md
  tests/send-donation/Znap.toml
  tests/send-donation/actions.json
  tests/send-donation/collections/my-actions/Cargo.toml
  tests/send-donation/collections/my-actions/src/lib.rs
  tests/send-donation/package-lock.json
  tests/send-donation/package.json
  tests/send-donation/tests/my-actions.ts
  tests/send-donation/tests/utils.ts
  tests/send-donation/tsconfig.json
  znap/src/env.rs
Labels: cli, ci

#86 Correct propagate env vars on child process
  znap-cli/src/commands/deploy.rs
  znap-cli/src/commands/serve.rs
  znap-cli/src/commands/test.rs
  znap-cli/src/utils/mod.rs
Labels: bug, cli, core

#87 Custom, Prefix and Shorthand Path
  tests/send-donation/collections/my-actions/src/lib.rs
  tests/send-donation/tests/my-actions.ts
  znap-syn/src/codegen/action/mod.rs
  znap-syn/src/codegen/action/path.rs
  znap-syn/src/codegen/action/to_metadata.rs
  znap-syn/src/common.rs
  znap-syn/src/lib.rs
Labels: enhancement, core

#92 fix: false positive tests
  znap-cli/src/utils/mod.rs
Labels: bug, cli

#94 fix: generate suttle secrets file
  znap-cli/src/commands/build.rs
  znap-cli/src/commands/deploy.rs
  znap-cli/src/commands/serve.rs
  znap-cli/src/commands/test.rs
  znap-cli/src/utils/mod.rs
Labels: bug, cli
